version: '0'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./protobuf
        target: /protobuf
    tty: true
    ports:
      - "$WEB_SERVER_PORT:$WEB_SERVER_PORT"