version: '2'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BAZEL_VERSION: "${BAZEL_VERSION}"
    image: "${OCI_REPOSITORY}:${BAZEL_VERSION}"
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./protobuf
        target: /protobuf
    env_file: .env
    tty: true
    ports:
      - "$WEB_SERVER_PORT:$WEB_SERVER_PORT"