version: '0'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app
    env_file: .env
    tty: true
    ports:
      - "$WEB_SERVER_PORT:$WEB_SERVER_PORT"