name: ci-front-prod

on:
  pull_request:
    branches: [main]
    paths: 'app/lib/**'
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    
    env:
      TETRIS_API: ${{ secrets.TETRIS_API_PROD }}
      TETRIS_COGNITO_USER_POOL_ID: ${{ secrets.TETRIS_COGNITO_USER_POOL_ID_PROD }}
      TETRIS_COGNITO_APP_CLIENT_ID: ${{ secrets.TETRIS_COGNITO_APP_CLIENT_ID_PROD }}
      TETRIS_COGNITO_WEB_DOMAIN: ${{ secrets.TETRIS_COGNITO_WEB_DOMAIN_PROD }}
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get
        working-directory: ./app

      - name: Flutter build
        run: make build
        working-directory: ./app
